/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "../../MiddleWares/MCAL/TIMR/TIM_interface.h"
void GPIO_Init(void) {
    // Enable clock for GPIOA
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;

    // Set PA0 as Alternate Function Push-Pull (AFPP) for PWM
    GPIOA->CRL &= ~GPIO_CRL_MODE0;          // Clear mode bits for PA0
    GPIOA->CRL |= GPIO_CRL_MODE0_1;         // Set PA0 as output at 2 MHz
    GPIOA->CRL &= ~GPIO_CRL_CNF0;           // Clear CNF bits
    GPIOA->CRL |= GPIO_CRL_CNF0_1;          // Set PA0 to alternate function
}
int main(void)
{

	GPIO_Init();
	TIM_initPWM(TIM2, 1, 100);
	TIM_writePWM(TIM2, 1, 2.5);
	while (1)
	{

	}

}


//#include "stm32f1xx.h"  // STM32F103 header file
//
//void GPIO_Init(void) {
//    // Enable clock for GPIOA
//    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
//
//    // Set PA0 as Alternate Function Push-Pull (AFPP) for PWM
//    GPIOA->CRL &= ~GPIO_CRL_MODE0;          // Clear mode bits for PA0
//    GPIOA->CRL |= GPIO_CRL_MODE0_1;         // Set PA0 as output at 2 MHz
//    GPIOA->CRL &= ~GPIO_CRL_CNF0;           // Clear CNF bits
//    GPIOA->CRL |= GPIO_CRL_CNF0_1;          // Set PA0 to alternate function
//}
//
//void TIM2_Init(void) {
//    // Enable clock for TIM2
//    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
//
//    // Set prescaler and auto-reload values for PWM frequency
//    TIM2->PSC = 72 - 1;    // Prescaler to get 1 MHz timer clock (8 MHz / 72)
//    TIM2->ARR = 1000 - 1;   // Set the period (PWM frequency = 1 kHz)
//
//    // Configure PWM mode for TIM2 Channel 1 (PA0)
//    TIM2->CCR1 = 100;       // 50% duty cycle (can change based on needs)
//    TIM2->CCMR1 &= ~TIM_CCMR1_OC1M;   // Clear OC1M bits
//    TIM2->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;   // PWM mode 1
//
//    // Enable output compare for TIM2 Channel 1 (PA0)
//    TIM2->CCER |= TIM_CCER_CC1E;  // Enable the output for Channel 1
//
//    // Enable the timer
//    TIM2->CR1 |= TIM_CR1_CEN;  // Enable the counter
//}
//
//int main(void) {
//    SystemInit();
//    GPIO_Init();  // Initialize PA0 for PWM
//    TIM2_Init();  // Initialize TIM2 for PWM output
//
//    while (1) {
//        // Main loop
//        // PWM signal is automatically generated by the timer.
//    }
//}
